Default: &defaults
  database: Web.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Web_test.sqlite3
  <<: *defaults

Staging:
  database: Web_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Web_production.sqlite3
  poolsize: 100
  <<: *defaults
